### ISSUE TITLE
A maintained fork

### ISSUE THREAD

**Issue by someniatko** [alexeyshockov/iter-psalm-plugin#1]
Hi there! I love nikic\iter and I also do like psalm static analyzer and use it daily. Therefore I came to this plugin. Unfortunately, I see it's not maintained anymore. Therefore I decided to create my own fork. I take responsibility to maintain it and fix issues. I hope it will be useful for someone.

I will soon add stubs for other files, not only `iter.php`

https://github.com/someniatko/iter-psalm-plugin
https://packagist.org/packages/someniatko/iter-psalm-plugin

**Comment by alexeyshockov** [comment]
I don't know why you decided that this repo is not maintained. IMO opening a PR first would be better than forking silently.

Anyway you are free to do basically anything with the code, but I would appreciate a PR (don't have time at the moment to reflect the latest Psalm's changes here, unfortunately).
